### ISSUE TITLE
Unable to logout, edit profile

### ISSUE THREAD

**Issue by sherrpass** [LingoClash/LingoClash#55] opened 2022-04-15 06:42 UTC
Unable to edit profile: please fill in all fields error is seen.
<img width="218" alt="image" src="https://user-images.githubusercontent.com/49825021/163532058-49e4f49e-605a-49fc-8ae0-c36a3c4d6a0d.png">

Changed email from c@c.com to d@d.com, then tried to change from d@d.com back to c@c.com but got
<img width="271" alt="image" src="https://user-images.githubusercontent.com/49825021/163534122-8afa9d42-a6a2-4e4a-a8a3-6324edf86127.png">

Unable to logout, after pressing button.

**Comment by CrownKira** [comment] 2022-04-16 16:37
Duplicate of #65  #66

**Closed as completed by CrownKira** 2022-04-16 16:37 UTC
